export const ACTION_TYPES = {
  FETCH_TOP_FREE_APPS: "FETCH_TOP_FREE_APPS",
  FETCH_TOP_GROSSING_APPS: "FETCH_TOP_GROSSING_APPS",
  FETCH_APPS_RATIING: "FETCH_APPS_RATIING",
  EDIT_SEARCH_KEYWORDS: "EDIT_SEARCH_KEYWORDS",
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR"
};

export const SECTION_TITLES = {
  RECOMMANDATIONS: "推介",
  TOP_FREE_APPS: "免費App排行"
};

export const DATA_KEY = {
  TOP_FREE_APPS: "TOP_FREE_APPS",
  TOP_GROSSING_APPS: "TOP_GROSSING_APPS"
};

export const MESSAGES = {
  NO_RATING: "(未有用戶評分)",
  LOADING_RATING: "正載入評分..",
  NO_MATCHING_DATA: "- 未找到相符結果 -",
  LOADING: "載入中..",
  FETCH_DATA_ERROR: "無法取得資料: 沒有網絡或API錯誤"
};
